### ISSUE TITLE
Broken web page

### ISSUE THREAD

**Issue by ghost** [shrimpza/aurial#22]
Hi, I tried to "install" it following the instructions, 

> To "install", simply extract the archive into a directory exposed via an HTTP service (there's no need for any server-side scripting or database), and browse to that location.

but the index web page appears broken in my browser.

![screenshot_20170816_174745](https://user-images.githubusercontent.com/29920421/29372345-264004ec-82ab-11e7-87f0-d4f91d826af2.png)
![screenshot_20170816_174815](https://user-images.githubusercontent.com/29920421/29372350-2a8011e6-82ab-11e7-9f62-07093d94ebb9.png)

Any suggestion?

**Comment by shrimpza** [comment]
Hi,

I'm sorry for the late response.

By the looks of things, it's failing to load the scripts remotely hosted on https://cdnjs.com/. I'm not sure if that was a temporary failure on their/CloudFlare side, or if something more fundamental has gone wrong.

Are you accessing Aurial via HTTP, or a `file://` location?

Are you using any browser addons like uMatrix which prevents cross-domain script loading? As a test, does https://shrimpza.github.io/aurial/ appear to load correctly for you?

**Comment by ghost** [comment]
Hi, I'm trying to access it via `file:// `(by double-clicking on index.html)
I'm using uBlock Origin, but I tried to deactivate the extension. Unfortunatetly, same result.

**Comment by shrimpza** [comment]
OK, it does typically need to be hosted behind an actual HTTP service, such as nginx or httpd.

Alternatively, you could try to simply edit `index,html` and prefix the cdnjs URLs with `http://`.

Unfortunately even then, it's possible you're going to run into browser security issues, preventing a `file://`-hosted page/script from accessing remote resources.

**Comment by ghost** [comment]
Thank for your answer! Do you know if it works with Ampache too?

**Comment by shrimpza** [comment]
Unlikely, unless Ampache is able to expose a Subsonic API.

Aurial was designed to work with Subsonic only.

Edit: I see that Ampache does have a Subsonic-compatible API, although it remains completely untested with Aurial, so your mileage may vary...
