### ISSUE TITLE
Not able to use with an airsonic server

### ISSUE THREAD

**Issue by flaun** [shrimpza/aurial#28]
It's not possible do use your app with airsonic!
The error coming up is: Failed to connect to server: Network Error when attempting to fetch resource.

Any ideas?

**Comment by shrimpza** [comment]
I was not aware of Airsonic - I will give it a test and see if it works as expected.

In the mean time, are you running Aurial and Airsonic both behind either HTTP or HTTPS? Mixing protocols will fail with a network error.

**Comment by flaun** [comment]
I'm using Airsonic with HTTPS.
Not sure how I'm running Aurial. How can I check this?

thx for your quick answer:)

**Comment by shrimpza** [comment]
How did you launch Aurial? Is it deployed via NPM (`npm run start`) or are you serving it via a web service?

I believe Aurial on HTTP and Airsonic on HTTPS should work; however Aurial on HTTPS and Airsonic on HTTP will not.


I've also done a quick test using an out-of-the box `docker run` of Airsonic with my music mounted, and Aurial seems to function as expected, so I don't think there's any sort of difference in API between Subsonic and Airsonic

Perhaps verify your Airsonic logs and see what it says when you attempt a "test connection" from Aurial's settings page?

**Comment by flaun** [comment]
I'm trying to use Aurial via the Ubports app. So I guess it's a webapp. How could I choose the different ways to launch it? (By the way: Trying the live demo link with firefox on my laptop there comes up the same error!)
Unfortunately I'm not able to check the airsonic logs, at least not at the moment. I'm using the airsonic server of my brother.
But good to know, that airsonic should work too with Aurial!
And sorry for asking maybe stupid questions. I don't know that much about setting up the airsonic server and so on....

**Comment by legobuild** [comment]
I'm able to connect to my Airsonic server. I'm connecting over HTTPS on a separate web server. I have a separate issue where I can't drill down on artists, but that's likely a browser problem. Playlists work and play without issue.

**Comment by shrimpza** [comment]
I've switched to Airsonic for a while, and Aurial has been working without issues, and requires no special configuration or steps to work with Airsonic, so I'm closing this one.
