### ISSUE TITLE
String Playlists IDs

### ISSUE THREAD

**Issue by deluan** [shrimpza/aurial#29]
Thanks for your awesome client!

I'm developing a new subsonic-api compatible server, Navidrome, and found an issue while testing Aurial with it. It works pretty well for all functionality, except when adding songs to playlists. 

The problem seems to be caused by the fact that my server uses uuid (strings) as IDs, and looks like you're expecting the playlist ID to be a number:
https://github.com/shrimpza/aurial/blob/caab9b3589a65dcdad1c57640ebe2949aa78d465/src/js/jsx/playlist.js#L47

But the specification shows it can be a string:
https://github.com/airsonic/airsonic/blob/master/subsonic-rest-api/src/main/resources/subsonic-rest-api.xsd#L332

I'm already listing Aurial as a [compatible client](https://www.navidrome.org/docs/overview/#apps), but I just got a user complaining about this... :/

Can you please take a look? Thanks in advance!

**EDIT:** Let me know if you need a testing instance, I can create an account for you on my server

**Comment by shrimpza** [comment]
Hey,

Navidrome looks really cool, I've set up an instance on my home network and it seems to work great on its own, and out-the-box with Aurial :).

I'll certainly look into the playlist ID issue - it's been a while so I can't remember why I assumed it to be numeric only.
